# Generated by Django 6.0.7 on 2026-09-11 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.PositiveBigIntegerField(verbose_name='قیمت لحظه خرید (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='key',
            field=models.CharField(max_length=80, verbose_name='عنوان مشخصه'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='value',
            field=models.CharField(max_length=200, verbose_name='مقدار'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ پرداختی (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغوشده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='شناسه Authority')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='شناسه تراکنش')),
                ('gateway', models.CharField(default='zarinpal', max_length=50, verbose_name='درگاه پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره مرجع')),
                ('card_pan', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره کارت')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='shop.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداختها',
                'ordering': ['-created_at'],
            },
        ),
    ]
