# Generated by Django 6.0.7 on 2026-09-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderitem_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_first_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام خانوادگی گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_source',
            field=models.CharField(choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('whatsapp', 'واتس\u200cاپ'), ('google', 'گوگل'), ('friend', 'معرفی دوستان'), ('other', 'سایر')], default='other', max_length=20, verbose_name='از کجا با ما آشنا شدید؟'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='آدرس کامل تحویل'),
        ),
    ]
